### ISSUE TITLE
Not and editor command: UltiSnipsAddFileTypes

### ISSUE THREAD

**Issue by armw4** [adamclerk/vim-razor#1]
I receive this error when opening up razor view for editing. Is `vim-scripts/UltiSnips` required as an additional dependency? If so, could you please update the documentation to reflect this?

**Comment by armw4** [comment]
Probably best to check that `vim-scripts/UltiSnips` is defined or in use and conditionally activate it.

**Comment by armw4** [comment]
Found it here:

https://github.com/adamclerk/vim-razor/blob/master/ftplugin/razor.vim

**Comment by Kazark** [comment]
I also see this error:

![errorwhenopeningcshtmlfile](https://cloud.githubusercontent.com/assets/3661051/2701099/a0734f5e-c41c-11e3-9734-ebc023e0311b.png)

**Comment by axle07** [comment]
+1

**Comment by armw4** [comment]
@axle07 oh man...two years ago. forgot i ever made this :smiley:.

**Comment by axle07** [comment]
I'm assuming that this is because UltiSnips is a dependency?

**Comment by armw4** [comment]
I'm so far removed from this that I don't even know. Even surprised it's still happening.

**Comment by armw4** [comment]
Ha...actually not surprised. This plugin basically hasn't been updated since this issue was opened (like 2 years).
